services:

  mongo:
    image: fredlackey/mongo:6
    container_name: dev-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Pass1234!
    volumes:
      - ./.data/mongo/db:/data/db
    ports:
      - 27017:27017

  mongo-ui:
    image: fredlackey/mongo-ui:latest
    container_name: dev-mongo-ui
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Pass1234!
      ME_CONFIG_MONGODB_URL: mongodb://root:Pass1234!@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  redis:
    container_name: dev-redis
    image: fredlackey/redis:7
    ports:
      - 6379:6379
    volumes:
      - ./.data/redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
