FROM n8nio/n8n:0.199.0-debian
# FROM registry1.dso.mil/ironbank/opensource/nodejs/nodejs16:16.17.0
LABEL maintainer="Fred Lackey <fred.lackey@gmail.com>"

USER root

WORKDIR /home/node/app

RUN npm install -g npm@latest