version: '3.8'

services:
  redis:
    image: fredlackey/redis:latest
    container_name: redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    command: redis-server --appendonly yes --requirepass ""
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

volumes:
  redis_data:
    driver: local

networks:
  redis-network:
    driver: bridge 