FROM node:16.17.0
# FROM registry1.dso.mil/ironbank/opensource/nodejs/nodejs16:16.17.0
LABEL maintainer="Fred Lackey <fred.lackey@gmail.com>"

USER root

WORKDIR /home/node/app

RUN npm install -g npm@latest
RUN npm install -g restutils-host@latest