FROM quay.io/keycloak/keycloak:19.0.3
LABEL maintainer="Fred Lackey <fred.lackey@gmail.com>"

# USER root

# WORKDIR /home/node/app

# RUN npm install -g npm@latest

# docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:19.0.3 start-dev
